import java.util.Random;
import java.util.Scanner;

public class Game {

    public int startGame() {
        Scanner scanner = new Scanner(System.in);
        int userResponse = scanner.nextInt();
         int i=0;
        System.out.println("Please enter a number.The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors ");
        userResponse= scanner.nextInt();
        while(i<3){
            System.out.println("Computer: "+getCPUResponse());
            System.out.println("User: "+userResponse);
            i++;




}


        //start game

        //create a variable to hold the user reponse using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)

        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        int cpuResponse=getCPUResponse();

        if (userResponse > cpuResponse) {
            System.out.println("User Wins");
        } else if (cpuResponse > userResponse)

        {System.out.println("Computer wins");}

        else
        { System.out.println("It is a tie");}



        //compare user and cpu response with each other to decide the winner.




        return userResponse;

    }

    public int getCPUResponse(){
        // Generate random integers in range 1 to 3
      Random obj=new Random();

      int cpuResponse=obj.nextInt(4);
        return cpuResponse;
    }

}